name: Build and Test on Commit

on:
  push:
    branches:
      - master

jobs:
  build:

    name: "${{ matrix.os }} (Dart: ${{ matrix.dart-version }}, Code: ${{ matrix.code-version }})"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        dart-version: ["stable"]

    steps:

      - uses: actions/checkout@v1

      - name: Setup Dart ${{ matrix.dart-version }}
        uses: DanTup/gh-actions/setup-dart@v0.0.7
        with:
          channel: ${{ matrix.dart-version }}

      - name: Print Dart version
        run: dart --version

      - run: |
          pub global activate --no-executables devtools
          pub global activate --no-executables webdev
          pub global activate --no-executables stagehand
          pub global activate --no-executables args 1.5.0
          pub global activate --no-executables meta 1.1.6
          pub global activate --no-executables pedantic 1.4.0
        shell: pwsh
        
      - run: pub global list
